name: Backfill Historical GTI

on:
  workflow_dispatch: {}   # manual only

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests
      - name: Run backfill
        run: python backfill_historical.py
      - name: Show head of gti.json
        run: |
          echo "=== data/gti.json ==="
          head -n 60 data/gti.json || echo "gti.json missing"
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/gti.json
          git commit -m "Historical GTI backfill" || echo "No changes"
          git push
