name: Update Daily GTI

on:
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch Planetary Health
        run: python scripts/fetch_planetary.py

      - name: Fetch Global Sentiment
        run: python scripts/fetch_sentiment.py

      - name: Fetch Markets
        run: python scripts/fetch_markets.py

      - name: Update GTI
        run: python scripts/updater.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json data/live/*.json || true
          git commit -m "Automated daily update" || echo "No changes"
          git push
