name: Update Daily GTI

on:
  schedule:
    - cron: "20 2 * * *"   # 02:20 UTC daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo root (pre)
        run: |
          pwd
          ls -la
          echo "Python files in root:"
          ls -la *.py || true

      - name: Ensure data folders
        run: |
          mkdir -p data/live
          touch data/.gitkeep
          touch data/live/.gitkeep
          ls -la data
          ls -la data/live

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      # ---- Fetchers (all at repo root) ----
      - name: Fetch Planetary Health
        run: python fetch_planetary.py

      - name: Fetch Global Sentiment
        run: python fetch_sentiment.py

      - name: Fetch Markets
        run: python fetch_markets.py

      # ---- Updater ----
      - name: Update GTI
        run: python updater.py

      # ---- Diagnostics: show files + print JSON heads ----
      - name: Show generated files
        run: |
          echo "=== data ==="
          ls -la data
          echo "=== data/live ==="
          ls -la data/live || true
          echo "=== preview: data/status.json ==="
          if [ -f data/status.json ]; then head -n 80 data/status.json; else echo "status.json MISSING"; fi
          echo "=== preview: data/live/planetary.json ==="
          if [ -f data/live/planetary.json ]; then head -n 80 data/live/planetary.json; else echo "planetary.json MISSING"; fi
          echo "=== preview: data/live/sentiment.json ==="
          if [ -f data/live/sentiment.json ]; then head -n 80 data/live/sentiment.json; else echo "sentiment.json MISSING"; fi
          echo "=== preview: data/live/markets.json ==="
          if [ -f data/live/markets.json ]; then head -n 80 data/live/markets.json; else echo "markets.json MISSING"; fi

      # Upload data folder as artifact for inspection (optional but helpful)
      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-folder
          path: data

      # Commit & push any new/updated files
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automated daily update" || echo "No changes"
          git push
