name: Update Daily GTI

on:
  workflow_dispatch:
  schedule:
    - cron: '17 5 * * *'   # daily at 05:17 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run updater
        run: python3 updater.py

      - name: Show diff
        run: |
          git status
          git diff -- data/gti.json data/categories.json data/changelog.json || true

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: daily GTI update'
          file_pattern: |
            data/gti.json
            data/categories.json
            data/changelog.json
