name: Update Daily GTI

on:
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure data folders
        run: |
          mkdir -p data/live
          touch data/.gitkeep data/live/.gitkeep
          ls -la
          ls -la data
          ls -la data/live

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch Planetary Health
        run: python fetch_planetary.py
        continue-on-error: true

      - name: Fetch Global Sentiment
        run: python fetch_sentiment.py
        continue-on-error: true

      - name: Fetch Markets
        run: python fetch_markets.py
        continue-on-error: true

      - name: Update GTI
        run: python updater.py

      - name: Show generated files
        run: |
          echo "=== data ==="; ls -la data
          echo "=== data/live ==="; ls -la data/live || true
          echo "=== status.json ==="; if [ -f data/status.json ]; then cat data/status.json; else echo "status.json MISSING"; fi
          echo "=== planetary.json ==="; if [ -f data/live/planetary.json ]; then head -n 60 data/live/planetary.json; else echo "planetary.json MISSING"; fi
          echo "=== sentiment.json ==="; if [ -f data/live/sentiment.json ]; then head -n 60 data/live/sentiment.json; else echo "sentiment.json MISSING"; fi
          echo "=== markets.json ==="; if [ -f data/live/markets.json ]; then head -n 60 data/live/markets.json; else echo "markets.json MISSING"; fi

      - name: Upload data artifact
        uses: actions/upload-artifact@v4
        with:
          name: data-folder
          path: data

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Automated daily update" || echo "No changes"
          git push
